### ISSUE TITLE
v3.10.1 doesn’t work on MacOS 10.14 any more

### ISSUE THREAD

**Issue by fiee** [nextcloud-releases/desktop#2]
While 3.10.0 still works, and the website still claims the desktop client would work with MacOS 10.14+, 3.10.1 seems to require at least MacOS 12.

This is a very surprising change in a minor release that even gets installed more or less automatically.

**Comment by mgallien** [comment]
I am sorry for the inconvenience but we had no technical choice to do otherwise.
Keep in mind that we do our best to maintain the compatibility with old operating system releases.
Keep also in mind that using a release that is no longer supported by its vendor or by its community (if it is free and open source software) is generally a bad practice security wise
We indeed have a practical issue with macOS where it is definitely not easy to check the state on the many releases that are in use at any given time. We would have to do real work to keep the compatibility. That is not cost free.
