### ISSUE TITLE
Nexcloud desktop 3.13.0 crash on surface go 2 windows 11

### ISSUE THREAD

**Issue by tigernero79** [nextcloud-releases/desktop#9]
after updating from version 3.12.0 to 3.13.0 nextcloud on surface go 2 original windows 11 crashes, in the sense that it starts, and after 2 seconds the app closes, I don't know where to get logs that can help you.

if I put the 3.12.0 back everything works again

Greetings

**Comment by matvit92** [comment]
I have the same issue, all time crashing when using external location (not on system drive). Versions 3.12.3 and 3.12.4 working OK.

**Comment by matvit92** [comment]
Agree, i have two accounts logged in. One using local storage, second using SD card as storage. When i delete second account, everything is OK and client working correctly. When i re-add second account with SD card strorage, client crashing. Maybe it will be better add this issue here: https://github.com/nextcloud/desktop/issues

**Comment by mgallien** [comment]
please do not report issue with the software on this repository
this one, we may appreciate issues with our release process (like missing files or broken links)
